Resources:
  badatzapilambdaServiceRole882253AB:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
    Metadata:
      aws:cdk:path: badatz-api-lambda-stack-ts/badatz_api_lambda/ServiceRole/Resource
  badatzapilambdaSecurityGroup40E1B1B2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Automatic security group for Lambda Function badatzapilambdastacktsbadatzapilambdaF94DC617
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      VpcId: vpc-000442496728ac699
    Metadata:
      aws:cdk:path: badatz-api-lambda-stack-ts/badatz_api_lambda/SecurityGroup/Resource
  badatzapilambdaA540EC2F:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-590781477698-us-east-1
        S3Key: ea4a640fcc5494495da83863684b1f05b8d75308fe03e4f95b93a63c925fdf8c.zip
      Handler: handler.handler
      Role:
        Fn::GetAtt:
          - badatzapilambdaServiceRole882253AB
          - Arn
      Runtime: nodejs18.x
      Timeout: 60
      VpcConfig:
        SecurityGroupIds:
          - Fn::GetAtt:
              - badatzapilambdaSecurityGroup40E1B1B2
              - GroupId
        SubnetIds:
          - subnet-05b3d3873e1492352
          - subnet-0ca05b92ba73b7bfc
          - subnet-0b164baf36c8f374b
          - subnet-0e9d6809a7b2f8f60
          - subnet-0ee139fa0bcd1e1d5
    DependsOn:
      - badatzapilambdaServiceRole882253AB
    Metadata:
      aws:cdk:path: badatz-api-lambda-stack-ts/badatz_api_lambda/Resource
      aws:asset:path: /home/tmax/development/badatz-monorepo/badatz-api/typescript-api/app/dist
      aws:asset:is-bundled: false
      aws:asset:property: Code
  badatzapilambdaInvoke2UTWxhlfyqbT5FTn5jvgbLgjFfJwzswGk55DU1HYDCACCDC8:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - badatzapilambdaA540EC2F
          - Arn
      Principal: elasticloadbalancing.amazonaws.com
    Metadata:
      aws:cdk:path: badatz-api-lambda-stack-ts/badatz_api_lambda/Invoke2UTWxhlfyqbT5FTn--5jvgbLgj+FfJwzswGk55DU1H--Y=
  testAPI7149245E:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: testAPI
    Metadata:
      aws:cdk:path: badatz-api-lambda-stack-ts/testAPI/Resource
  testAPIDeploymentB36F0A7314222971722b995142105d2f2b8b485b:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: Automatically created by the RestApi construct
      RestApiId:
        Ref: testAPI7149245E
    DependsOn:
      - testAPIproxyANY822EBEDE
      - testAPIproxyC8BE8CDF
      - testAPIANY8D7F282E
    Metadata:
      aws:cdk:path: badatz-api-lambda-stack-ts/testAPI/Deployment/Resource
  testAPIDeploymentStageprod050F5FA4:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId:
        Ref: testAPIDeploymentB36F0A7314222971722b995142105d2f2b8b485b
      RestApiId:
        Ref: testAPI7149245E
      StageName: prod
    Metadata:
      aws:cdk:path: badatz-api-lambda-stack-ts/testAPI/DeploymentStage.prod/Resource
  testAPIproxyC8BE8CDF:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - testAPI7149245E
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: testAPI7149245E
    Metadata:
      aws:cdk:path: badatz-api-lambda-stack-ts/testAPI/Default/{proxy+}/Resource
  testAPIproxyANYApiPermissionbadatzapilambdastacktstestAPI7D283674ANYproxy32E8D1F5:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - badatzapilambdaA540EC2F
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:us-east-1:590781477698:"
            - Ref: testAPI7149245E
            - /
            - Ref: testAPIDeploymentStageprod050F5FA4
            - /*/*
    Metadata:
      aws:cdk:path: badatz-api-lambda-stack-ts/testAPI/Default/{proxy+}/ANY/ApiPermission.badatzapilambdastacktstestAPI7D283674.ANY..{proxy+}
  testAPIproxyANYApiPermissionTestbadatzapilambdastacktstestAPI7D283674ANYproxy9E820B07:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - badatzapilambdaA540EC2F
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:us-east-1:590781477698:"
            - Ref: testAPI7149245E
            - /test-invoke-stage/*/*
    Metadata:
      aws:cdk:path: badatz-api-lambda-stack-ts/testAPI/Default/{proxy+}/ANY/ApiPermission.Test.badatzapilambdastacktstestAPI7D283674.ANY..{proxy+}
  testAPIproxyANY822EBEDE:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - badatzapilambdaA540EC2F
                  - Arn
              - /invocations
      ResourceId:
        Ref: testAPIproxyC8BE8CDF
      RestApiId:
        Ref: testAPI7149245E
    Metadata:
      aws:cdk:path: badatz-api-lambda-stack-ts/testAPI/Default/{proxy+}/ANY/Resource
  testAPIANYApiPermissionbadatzapilambdastacktstestAPI7D283674ANYEACEB020:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - badatzapilambdaA540EC2F
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:us-east-1:590781477698:"
            - Ref: testAPI7149245E
            - /
            - Ref: testAPIDeploymentStageprod050F5FA4
            - /*/
    Metadata:
      aws:cdk:path: badatz-api-lambda-stack-ts/testAPI/Default/ANY/ApiPermission.badatzapilambdastacktstestAPI7D283674.ANY..
  testAPIANYApiPermissionTestbadatzapilambdastacktstestAPI7D283674ANY6223847B:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - badatzapilambdaA540EC2F
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:us-east-1:590781477698:"
            - Ref: testAPI7149245E
            - /test-invoke-stage/*/
    Metadata:
      aws:cdk:path: badatz-api-lambda-stack-ts/testAPI/Default/ANY/ApiPermission.Test.badatzapilambdastacktstestAPI7D283674.ANY..
  testAPIANY8D7F282E:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - badatzapilambdaA540EC2F
                  - Arn
              - /invocations
      ResourceId:
        Fn::GetAtt:
          - testAPI7149245E
          - RootResourceId
      RestApiId:
        Ref: testAPI7149245E
    Metadata:
      aws:cdk:path: badatz-api-lambda-stack-ts/testAPI/Default/ANY/Resource
  ALBListenerbadatzapiFCDFA676:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - TargetGroupArn:
            Ref: badatzapitgC58E3340
          Type: forward
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - rp.api.insightxc.com
      ListenerArn: arn:aws:elasticloadbalancing:us-east-1:590781477698:listener/app/badatz-internal-alb/1d3fb2c2a2df313e/ab9988b8f0a79087
      Priority: 90
    Metadata:
      aws:cdk:path: badatz-api-lambda-stack-ts/ALBListener/badatz-api/Resource
  badatzapitgC58E3340:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      TargetType: lambda
      Targets:
        - Id:
            Fn::GetAtt:
              - badatzapilambdaA540EC2F
              - Arn
    DependsOn:
      - badatzapilambdaInvoke2UTWxhlfyqbT5FTn5jvgbLgjFfJwzswGk55DU1HYDCACCDC8
    Metadata:
      aws:cdk:path: badatz-api-lambda-stack-ts/badatz-api-tg/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/1VQwU7DMAz9lt2zwIaQuG4guAwxFe6Tl5rOW5pEibNRVfl3khamTork9+zYfs9LuVg8yvsZXMJc1ae5pr3sPxnUSVQYbPQKRa7teg3tvgbZv0ajmKwRz99mirfoWwohsyQIWtlXVmMplJhEeNhBCMhBrkrIXK6jOiGvIaBAtcxbUUVP3L15G13pvEkkAY4aYLxAJ/vNoCYr5JWjYcsffEGnbdei4ZKdsOypGfSM4N/csH7r7U93tTtOG/E78sHWJTWiJFBDYFLaQr0HDUaRac5Z/co5TQrKOTYUGA36Ko4XuOGTf1/gG+Sr3QlNSQxnKlrz/FL9iOwiT8UlYWyN8hjuzosnmd9ydgxEcx8NU4uyGuMvIPVzJuIBAAA=
    Metadata:
      aws:cdk:path: badatz-api-lambda-stack-ts/CDKMetadata/Default
Outputs:
  testAPIEndpoint0E24C440:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: testAPI7149245E
          - .execute-api.us-east-1.
          - Ref: AWS::URLSuffix
          - /
          - Ref: testAPIDeploymentStageprod050F5FA4
          - /
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

