Resources:
  badatzapilambdaServiceRole882253AB:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
    Metadata:
      aws:cdk:path: LocalTesting/badatz_api_lambda/ServiceRole/Resource
  badatzapilambdaSecurityGroup40E1B1B2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Automatic security group for Lambda Function LocalTestingbadatzapilambdaA16112FD
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      VpcId: vpc-000442496728ac699
    Metadata:
      aws:cdk:path: LocalTesting/badatz_api_lambda/SecurityGroup/Resource
  badatzapilambdaA540EC2F:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-590781477698-us-east-1
        S3Key: 9f627520b76d2caa6119e9e83e098fe7c33b3f2dc5a6f61e362e8db003d2d233.zip
      Handler: /home/tmax/development/badatz-monorepo/badatz-api/typescript-api/app/handler.handler
      Role:
        Fn::GetAtt:
          - badatzapilambdaServiceRole882253AB
          - Arn
      Runtime: nodejs18.x
      Timeout: 60
      VpcConfig:
        SecurityGroupIds:
          - Fn::GetAtt:
              - badatzapilambdaSecurityGroup40E1B1B2
              - GroupId
        SubnetIds:
          - subnet-05b3d3873e1492352
          - subnet-0ca05b92ba73b7bfc
          - subnet-0b164baf36c8f374b
          - subnet-0e9d6809a7b2f8f60
          - subnet-0ee139fa0bcd1e1d5
    DependsOn:
      - badatzapilambdaServiceRole882253AB
    Metadata:
      aws:cdk:path: LocalTesting/badatz_api_lambda/Resource
      aws:asset:path: /home/tmax/development/badatz-monorepo/badatz-api/typescript-api/app/dist
      aws:asset:is-bundled: false
      aws:asset:property: Code
  badatzapilambdaInvoke2UTWxhlfyqbT5FTn5jvgbLgjFfJwzswGk55DU1HYDCACCDC8:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - badatzapilambdaA540EC2F
          - Arn
      Principal: elasticloadbalancing.amazonaws.com
    Metadata:
      aws:cdk:path: LocalTesting/badatz_api_lambda/Invoke2UTWxhlfyqbT5FTn--5jvgbLgj+FfJwzswGk55DU1H--Y=
  ALBListenerbadatzapiFCDFA676:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - TargetGroupArn:
            Ref: badatzapitgC58E3340
          Type: forward
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - rp.api.insightxc.com
      ListenerArn: arn:aws:elasticloadbalancing:us-east-1:590781477698:listener/app/badatz-internal-alb/1d3fb2c2a2df313e/ab9988b8f0a79087
      Priority: 90
    Metadata:
      aws:cdk:path: LocalTesting/ALBListener/badatz-api/Resource
  badatzapitgC58E3340:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      TargetType: lambda
      Targets:
        - Id:
            Fn::GetAtt:
              - badatzapilambdaA540EC2F
              - Arn
    DependsOn:
      - badatzapilambdaInvoke2UTWxhlfyqbT5FTn5jvgbLgjFfJwzswGk55DU1HYDCACCDC8
    Metadata:
      aws:cdk:path: LocalTesting/badatz-api-tg/Resource
  testAPI7149245E:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: testAPI
    Metadata:
      aws:cdk:path: LocalTesting/testAPI/Resource
  testAPICloudWatchRole9F659978:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: LocalTesting/testAPI/CloudWatchRole/Resource
  testAPIAccount85A13684:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - testAPICloudWatchRole9F659978
          - Arn
    DependsOn:
      - testAPI7149245E
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: LocalTesting/testAPI/Account
  testAPIDeploymentB36F0A73b4faa222c0dc784f75e4c5d4fa870465:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: Automatically created by the RestApi construct
      RestApiId:
        Ref: testAPI7149245E
    DependsOn:
      - testAPIproxyANY822EBEDE
      - testAPIproxyC8BE8CDF
      - testAPIANY8D7F282E
    Metadata:
      aws:cdk:path: LocalTesting/testAPI/Deployment/Resource
  testAPIDeploymentStageprod050F5FA4:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId:
        Ref: testAPIDeploymentB36F0A73b4faa222c0dc784f75e4c5d4fa870465
      RestApiId:
        Ref: testAPI7149245E
      StageName: prod
    DependsOn:
      - testAPIAccount85A13684
    Metadata:
      aws:cdk:path: LocalTesting/testAPI/DeploymentStage.prod/Resource
  testAPIproxyC8BE8CDF:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - testAPI7149245E
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: testAPI7149245E
    Metadata:
      aws:cdk:path: LocalTesting/testAPI/Default/{proxy+}/Resource
  testAPIproxyANYApiPermissionLocalTestingtestAPI1F441DC7ANYproxyE7810C09:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - badatzapilambdaA540EC2F
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:us-east-1:590781477698:"
            - Ref: testAPI7149245E
            - /
            - Ref: testAPIDeploymentStageprod050F5FA4
            - /*/*
    Metadata:
      aws:cdk:path: LocalTesting/testAPI/Default/{proxy+}/ANY/ApiPermission.LocalTestingtestAPI1F441DC7.ANY..{proxy+}
  testAPIproxyANYApiPermissionTestLocalTestingtestAPI1F441DC7ANYproxy04003E61:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - badatzapilambdaA540EC2F
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:us-east-1:590781477698:"
            - Ref: testAPI7149245E
            - /test-invoke-stage/*/*
    Metadata:
      aws:cdk:path: LocalTesting/testAPI/Default/{proxy+}/ANY/ApiPermission.Test.LocalTestingtestAPI1F441DC7.ANY..{proxy+}
  testAPIproxyANY822EBEDE:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :apigateway:us-east-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - badatzapilambdaA540EC2F
                  - Arn
              - /invocations
      ResourceId:
        Ref: testAPIproxyC8BE8CDF
      RestApiId:
        Ref: testAPI7149245E
    Metadata:
      aws:cdk:path: LocalTesting/testAPI/Default/{proxy+}/ANY/Resource
  testAPIANYApiPermissionLocalTestingtestAPI1F441DC7ANY2B7A36D6:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - badatzapilambdaA540EC2F
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:us-east-1:590781477698:"
            - Ref: testAPI7149245E
            - /
            - Ref: testAPIDeploymentStageprod050F5FA4
            - /*/
    Metadata:
      aws:cdk:path: LocalTesting/testAPI/Default/ANY/ApiPermission.LocalTestingtestAPI1F441DC7.ANY..
  testAPIANYApiPermissionTestLocalTestingtestAPI1F441DC7ANY6C7FD37D:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - badatzapilambdaA540EC2F
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:us-east-1:590781477698:"
            - Ref: testAPI7149245E
            - /test-invoke-stage/*/
    Metadata:
      aws:cdk:path: LocalTesting/testAPI/Default/ANY/ApiPermission.Test.LocalTestingtestAPI1F441DC7.ANY..
  testAPIANY8D7F282E:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :apigateway:us-east-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - badatzapilambdaA540EC2F
                  - Arn
              - /invocations
      ResourceId:
        Fn::GetAtt:
          - testAPI7149245E
          - RootResourceId
      RestApiId:
        Ref: testAPI7149245E
    Metadata:
      aws:cdk:path: LocalTesting/testAPI/Default/ANY/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/1VQTU/DMAz9LbtngQ0hce1AcBliKtwnLzXFW5pEibNRVfnvJK0YRYrk9+z44721XK3u5e0CLmGpmtNS00EO7wzqJGoMNnqFItf2g4bu0IAcnqNRTNaIx08zxzv0HYWQWRIEnRxqq7EUSkwi3O0hBOQgqxIyl5uoTsgbCChQrfNWVNET9y/eRlc6/yWSQA2BSWkLzQE0GEWmPee+yjlNCsohWwqMBn0dp93/+OzfB/gW+bpoRpMARy0wXqCXw3YUnY3gytEo5g9WStloWDyh07bvMMOcnbHsYjteMYFfO0fBO2+/+6vB0+AJvyJ/2aakJpSSGB0rQ7LgUniL7CLPu5IwtkF5DDfn1YPMb704BqKlzwdSh7Ke4g9/X3Ew7QEAAA==
    Metadata:
      aws:cdk:path: LocalTesting/CDKMetadata/Default
Outputs:
  testAPIEndpoint0E24C440:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: testAPI7149245E
          - .execute-api.us-east-1.
          - Ref: AWS::URLSuffix
          - /
          - Ref: testAPIDeploymentStageprod050F5FA4
          - /
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

